In [2]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("output/labeled_dataset.csv")
df.head()

,repo,repo_url,stars,file_path,file_size,mi_score,avg_cc,max_cc,loc,lloc,sloc,comments,blank,comment_ratio,quality_label,code
0,public-apis/public-apis,https://github.com/public-apis/public-apis,424462,scripts/tests/test_validate_format.py,18154,35.41,1.72,4,466,253,362,3,103,0.012,bad,# -*- coding: utf-8 -*-\n\nimport unittest\n\n...
1,public-apis/public-apis,https://github.com/public-apis/public-apis,424462,scripts/tests/test_validate_links.py,5725,100.00,1.36,2,172,82,132,1,39,0.012,good,# -*- coding: utf-8 -*-\n\nimport unittest\n\n...
2,public-apis/public-apis,https://github.com/public-apis/public-apis,424462,scripts/validate/format.py,8464,39.64,4.18,14,277,175,183,9,85,0.051,bad,# -*- coding: utf-8 -*-\n\nimport re\nimport s...
3,public-apis/public-apis,https://github.com/public-apis/public-apis,424462,scripts/validate/links.py,8032,52.87,3.64,8,273,136,158,2,85,0.015,medium,# -*- coding: utf-8 -*-\n\nimport re\nimport s...
4,EbookFoundation/free-programming-books,https://github.com/EbookFoundation/free-progra...,385637,scripts/rtl_ltr_linter.py,27037,40.34,17.33,57,605,206,255,142,129,0.689,bad,"#!/usr/bin/env python3\n""""""\nRTL/LTR Markdown ..."

In [6]:
df.tail()

,repo,repo_url,stars,file_path,file_size,mi_score,avg_cc,max_cc,loc,lloc,sloc,comments,blank,comment_ratio,quality_label,code
1001,google/python-fire,https://github.com/google/python-fire,28171,fire/parser.py,4697,67.28,3.00,8,132,55,47,22,24,0.400,good,# Copyright (C) 2018 Google Inc.\n#\n# License...
1002,google/python-fire,https://github.com/google/python-fire,28171,fire/parser_fuzz_test.py,3041,70.92,10.50,11,94,58,64,26,11,0.448,bad,# Copyright (C) 2018 Google Inc.\n#\n# License...
1003,google/python-fire,https://github.com/google/python-fire,28171,fire/parser_test.py,6379,67.54,1.05,2,140,88,98,16,25,0.182,good,# Copyright (C) 2018 Google Inc.\n#\n# License...
1004,google/python-fire,https://github.com/google/python-fire,28171,fire/test_components.py,11723,45.89,1.38,3,568,291,269,32,199,0.110,medium,# Copyright (C) 2018 Google Inc.\n#\n# License...
1005,google/python-fire,https://github.com/google/python-fire,28171,fire/test_components_bin.py,807,69.54,1.00,1,28,7,6,13,6,1.857,good,# Copyright (C) 2018 Google Inc.\n#\n# License...

In [7]:
df.isnull().sum()

repo             0
repo_url         0
stars            0
file_path        0
file_size        0
mi_score         0
avg_cc           0
max_cc           0
loc              0
lloc             0
sloc             0
comments         0
blank            0
comment_ratio    0
quality_label    0
code             0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1006 entries, 0 to 1005
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   repo           1006 non-null   object
 1   repo_url       1006 non-null   object
 2   stars          1006 non-null   int64
 3   file_path      1006 non-null   object
 4   file_size      1006 non-null   int64
 5   mi_score       1006 non-null   float64
 6   avg_cc         1006 non-null   float64
 7   max_cc         1006 non-null   int64
 8   loc            1006 non-null   int64
 9   lloc           1006 non-null   int64
 10  sloc           1006 non-null   int64
 11  comments       1006 non-null   int64
 12  blank          1006 non-null   int64
 13  comment_ratio  1006 non-null   float64
 14  quality_label  1006 non-null   object
 15  code           1006 non-null   object
dtypes: float64(3), int64(8), object(5)
memory usage: 125.9+ KB